# Generated by Django 4.2 on 2023-05-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twgobackend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
