# Generated by Django 4.2 on 2023-05-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twgobackend', '0006_alter_message_recipient_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAdmin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
