# Generated by Django 4.2 on 2023-05-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twgobackend', '0008_customadmin_customsuperadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
