# Generated by Django 4.2 on 2023-05-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twgobackend', '0009_customuser_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAdmin',
        ),
        migrations.DeleteModel(
            name='CustomSuperAdmin',
        ),
    ]
